version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - ./data/postgres:/var/lib/postgresql/data
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    environment:
      VITE_URL: http://backend:8000
    ports:
      - "3333:80"
    restart: on-failure

  backend:
    build:
      context: .
      dockerfile: ./config/Dockerfile
    container_name: investigators_backend
    volumes:
      - ./backend/:/code
    restart: always
    links:
      - db
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: ['make', 'django']
