version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - ./data/postgres:/var/lib/postgresql/data
  frontend:
    image: node:latest
    container_name: cogntive_frontend
    volumes:
      - ./frontend:/frontend
    working_dir: /frontend
    command: 'npm run dev'
    environment:
      VITE_URL: http://localhost:8000
    ports:
      - "3333:3333"
    restart: on-failure

  backend:
    build:
      context: .
      dockerfile: ./config/Dockerfile
    container_name: cogntive_backend
    volumes:
      - ./backend/:/code
    restart: always
    links:
      - db
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: ['make', 'django']
