version: '3.8'
services:
  app:
    build:
      dockerfile: ./Dockerfile
    container_name: ai-licensing_backend
    restart: always
    links:
      - db
    depends_on:
      - db
    networks:
      - web_net
    ports:
      - "8000:8000"
    command: python3 manage.py runserver
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local

networks:
  web_net:

