# Generated by Django 4.1.2 on 2022-10-20 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ManyToManyField(blank=True, related_name='organization', to='organization.organization'),
        ),
    ]
