// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ClientModal: typeof import('./components/ClientModal.vue')['default']
    ClientTable: typeof import('./components/ClientTable.vue')['default']
    ComboBox: typeof import('./components/ComboBox.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    Menu: typeof import('./components/Menu.vue')['default']
    OrganizationModal: typeof import('./components/OrganizationModal.vue')['default']
    OrganizationTable: typeof import('./components/OrganizationTable.vue')['default']
    Pagination: typeof import('./components/Pagination.vue')['default']
    Profile: typeof import('./components/Profile.vue')['default']
    ProfileLoading: typeof import('./components/ProfileLoading.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Statistic: typeof import('./components/Statistic.vue')['default']
    Table: typeof import('./components/Table.vue')['default']
    TableLoading: typeof import('./components/TableLoading.vue')['default']
    TransactionDashboard: typeof import('./components/TransactionDashboard.vue')['default']
    TransactionTable: typeof import('./components/TransactionTable.vue')['default']
    UserDashboard: typeof import('./components/UserDashboard.vue')['default']
    UserModal: typeof import('./components/UserModal.vue')['default']
    UserProfile: typeof import('./components/UserProfile.vue')['default']
    UsersTable: typeof import('./components/UsersTable.vue')['default']
  }
}
