# Generated by Django 4.1.2 on 2022-10-23 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_organizationapikey'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationapikey',
            options={'ordering': ('-created',), 'verbose_name': 'Device API key', 'verbose_name_plural': 'Device API keys'},
        ),
    ]
