# Generated by Django 4.1.2 on 2022-10-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_organization_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='hashed_key',
            field=models.CharField(max_length=1024),
        ),
    ]
