# Generated by Django 4.1.2 on 2022-11-18 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_alter_organization_hashed_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
