# Generated by Django 4.1.2 on 2022-11-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_organization_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='count',
        ),
        migrations.AddField(
            model_name='organization',
            name='balance',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
