# Generated by Django 4.1.2 on 2022-11-21 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_remove_organization_count_organization_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='balance',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
