# Generated by Django 4.1.2 on 2022-11-22 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0009_alter_organization_balance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationapikey',
            options={'ordering': ('-created',), 'verbose_name': 'Organization API key', 'verbose_name_plural': 'Organization API keys'},
        ),
    ]
